/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yzk_clibapp_JniUtils */

#ifndef _Included_com_yzk_clibapp_JniUtils
#define _Included_com_yzk_clibapp_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yzk_clibapp_JniUtils
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yzk_clibapp_JniUtils_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
